create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  subscription jsonb not null,
  timezone text not null default 'UTC',
  creatine_time time not null default '08:00',
  enabled boolean not null default true,
  last_creatine_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reminder_data jsonb not null default '{}'::jsonb,
  sent_reminders jsonb not null default '{}'::jsonb,
  user_id uuid references auth.users(id) on delete cascade
);

create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
